Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
from echemsuite.cyclicvoltammetry.read_input import CyclicVoltammetry
from echemsuite.graphicaltools import Palette, ColorShader

# Define a dictionary to store the experiments to be plotted
experiments = {}
experiments["Sample A"] = CyclicVoltammetry("/home/ppravatto/Dropbox/GES/Progetti/Experimental_data_analysis/GES-echem-suite/docs/utils/cv_example_A.DTA")
experiments["Sample B"] = CyclicVoltammetry("/home/ppravatto/Dropbox/GES/Progetti/Experimental_data_analysis/GES-echem-suite/docs/utils/cv_example_B.DTA")

# Define a color palette to be used in the plot
palette = Palette("vivid")

# Setup a figure object
plt.rcParams.update({'font.size': 18}) 
fig = plt.figure(figsize= (6, 6))

# Iterate over all the experiments in the dictionary
for i, (name, experiment) in enumerate(experiments.items()):

    # Define a shader with the basecolor provided by the palette
    shader = ColorShader(palette[i], levels=len(experiment), saturate=True, reversed=True, luminance_range=(0.6, 0.9))

    # Plot each trace recorded in the experiment
    for j, (current, voltage) in enumerate(experiment):
        plt.plot(voltage, [1e3*im for im in current], c=shader[j].RGB, label=name if j==0 else None)

# Add labels to the axes
plt.xlabel(r"V vs $\mathrm{V}_\mathrm{ref}$ [V]", size=20)
plt.ylabel("I [mA]", size=20)

# Add a grid to the plot
plt.grid(which="major", c="#DDDDDD")
plt.grid(which="minor", c="#EEEEEE")

# Plot the legend
plt.legend()

# Render the graph
plt.tight_layout()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 7[0m
[1;32m      5[0m [38;5;66;03m# Define a dictionary to store the experiments to be plotted[39;00m
[1;32m      6[0m experiments [38;5;241m=[39m {}
[0;32m----> 7[0m experiments[[38;5;124m"[39m[38;5;124mSample A[39m[38;5;124m"[39m] [38;5;241m=[39m [43mCyclicVoltammetry[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m/home/ppravatto/Dropbox/GES/Progetti/Experimental_data_analysis/GES-echem-suite/docs/utils/cv_example_A.DTA[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      8[0m experiments[[38;5;124m"[39m[38;5;124mSample B[39m[38;5;124m"[39m] [38;5;241m=[39m CyclicVoltammetry([38;5;124m"[39m[38;5;124m/home/ppravatto/Dropbox/GES/Progetti/Experimental_data_analysis/GES-echem-suite/docs/utils/cv_example_B.DTA[39m[38;5;124m"[39m)
[1;32m     10[0m [38;5;66;03m# Define a color palette to be used in the plot[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/echemsuite/cyclicvoltammetry/read_input.py:43[0m, in [0;36mCyclicVoltammetry.__init__[0;34m(self, path)[0m
[1;32m     41[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, path: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m     42[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misfile(path):
[0;32m---> 43[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe specified file `[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m` does not exist.[39m[38;5;124m"[39m)
[1;32m     45[0m     [38;5;28mself[39m[38;5;241m.[39m__filepath [38;5;241m=[39m path  [38;5;66;03m# path of input file[39;00m
[1;32m     46[0m     [38;5;28mself[39m[38;5;241m.[39msettings [38;5;241m=[39m {}  [38;5;66;03m# info from input header[39;00m

[0;31mValueError[0m: The specified file `/home/ppravatto/Dropbox/GES/Progetti/Experimental_data_analysis/GES-echem-suite/docs/utils/cv_example_A.DTA` does not exist.

